version: "3.7"
services:
  food-app:
    build:
      args:
        user: junior
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: food-app
    container_name: food-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - food-app

  food-db:
    image: mariadb:10.4
    container_name: food-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: food
      MYSQL_ROOT_PASSWORD: food
      MYSQL_PASSWORD: food
      MYSQL_USER: food
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '42332:3306'
    networks:
      - food-app
  
  food-phpmyadmin:
    depends_on:
      - food-db
    image: phpmyadmin/phpmyadmin
    container_name: food-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: food-db
      MYSQL_ROOT_PASSWORD: food
    networks:
      - food-app

  food-nginx:
    image: nginx:alpine
    container_name: food-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - food-app

  food-redis:
    image: redis:alpine
    container_name: food-redis
    expose:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - food-app

networks:
  food-app:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redis-data:
    driver: local
